-- CREATE DATABASE PWBOX;
USE PWBOX;

DROP TABLE IF EXISTS Roles CASCADE;
DROP TABLE IF EXISTS Folder CASCADE;
DROP TABLE IF EXISTS Usuari CASCADE;

CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `email` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `password` char(32) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQUE_EMAIL` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `folder`(
	`id` INT NOT NULL AUTO_INCREMENT,
  `creador` INT CHARACTER SET utf8mb4 NOT NULL DEFAULT 'root',
  `nom` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'new-folder',
  `path` VARCHAR(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (creador) REFERENCES user(`id`)
)ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `role`(
	`usuari` INT NOT NULL,
  `folder` INT NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'read',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `FOREIGN` KEY (`usuari`) REFERENCES Usuari(`id`),
  `FOREIGN` KEY (`folder`) REFERENCES Folder(`id`)
)ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
